### ISSUE TITLE
[BACKLOG] Redesign CU Get Reg

### ISSUE THREAD

**Issue by saenyakorn** [thinc-org/cugetreg#434]
### Problem

Currently, CU Get Reg is based on [MUI library](https://mui.com/) and the default style is [Material Design 2](https://m2.material.io/). 

[Material Design 2] was released in 2018. But in 2022, It looked old now. But, in May 2021, Google released a new Design System called [Material Design 3](https://m3.material.io/) which looks much better than the previous one. 

But I'm really sure that Thinc. designers can redesign much better. 

### Task Description

The main purpose of this issue is to redesign based on [Material Design 3](https://m3.material.io/) principle

# Current Focus
- [ ] Research and learn [Materil Design 3 principle] 
- [ ] Split the react custom components from `cugetreg-web` to the central `lib` folder (#391)

# Future Plan
- [ ] Redesign each component (Will create an issue for each component)
- [ ] Implement the new components and replace the old ones.

### Additional Context

- Each implemented component should be in `lib` folder
- Each implemented component should have 70%+ unit test coverage.

### Related Teams

- [X] Frontend
- [ ] Backend
- [ ] Data
- [X] Design
- [ ] Infra
- [ ] QA

### Task Advisors

@saenyakorn 
@natTP

**Comment by saenyakorn** [comment]
Useful guide for creating design system https://thedesignsystem.guide
